name: SDSR-SU
channels:
  - defaults
dependencies:
  - python=3.12           # Specify your desired Python version
  - pip                   # Include pip so you can install Python packages
  - pip:
      - -e .              # Install your package in editable mode (uses setup.py)